Rework devutils

diff --git a/bin/devutils/man b/bin/devutils/man
--- a/bin/devutils/man
+++ b/bin/devutils/man
@@ -1,28 +1,21 @@
 #!/usr/bin/env bash
 
-main() {
-	read -p "[man] program, utility, or function name: " program
-	[[ -z "$program" ]] && echo "Invalid input. Aborting." && return
+read -p "[man] program, utility, or function name: " program
+[[ -z "$program" ]] && echo "Invalid input. Aborting." && exit 1
 
-	man "$program"
-	retval=$?
-	[[ $retval -eq 0 ]] && exit 0
+man "$program"
+retval=$?
+[[ $retval -eq 0 ]] && exit 0
 
-	yesno "Fall back to \"$program --help\""
-	retval=$?
-	[[ $retval -eq 1 ]] && exit 1
+yesno "Fall back to \"$program --help\""
+retval=$?
+[[ $retval -eq 1 ]] && exit 2
 
-	command -v "$program"
-	retval=$?
-	if [[ $retval -eq 0 ]]; then
-		"$program" --help | less
-		exit 0
-	fi
+command -v "$program"
+retval=$?
+if [[ $retval -ne 0 ]]; then
+  echo "No such program found."
+  exit 1
+fi
 
-	echo "No such program found."
-}
-
-main
-
-read -p "Press [ENTER] to continue"
-exit 1
+"$program" --help | less
